CompuRent.DiegoTest.Presentation/Controllers/PurchaseDetailsController.cs
namespace CompuRent.DiegoTest.Presentation.Controllers
{
    using CompuRent.DiegoTest.Models.Entities;
    using CompuRent.DiegoTest.Services.BL.Facades;
    using CompuRent.DiegoTest.Services.DAL.Repositories.Facades;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.Threading.Tasks;

    /// <summary>
    /// Purchase Details Controller
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    public class PurchaseDetailsController : Controller
    {
        /// <summary>
        /// The purchease detai repository
        /// </summary>
        private readonly IGenericRepository<PurchaseDetailEntity> _purcheaseDetaiRepository;

        /// <summary>
        /// The album set repository
        /// </summary>
        private readonly IGenericRepository<AlbumSetEntity> _albumSetRepository;

        /// <summary>
        /// The shoping service bl
        /// </summary>
        private readonly IShopingServiceBL _shopingServiceBL;

        /// <summary>
        /// Initializes a new instance of the <see cref="PurchaseDetailsController" /> class.
        /// </summary>
        /// <param name="purcheaseDetaiRepository">The purchease detai repository.</param>
        /// <param name="albumSetRepository">The album set repository.</param>
        /// <param name="shopingServiceBL">The shoping service bl.</param>
        public PurchaseDetailsController(IGenericRepository<PurchaseDetailEntity> purcheaseDetaiRepository, IGenericRepository<AlbumSetEntity> albumSetRepository, IShopingServiceBL shopingServiceBL)
        {
            this._purcheaseDetaiRepository = purcheaseDetaiRepository;
            this._albumSetRepository = albumSetRepository;
            this._shopingServiceBL = shopingServiceBL;
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>Index View</returns>
        public async Task<IActionResult> Index()
        {
            var musicRadioIncDbContext = this._purcheaseDetaiRepository.Get().Include(p => p.AlbumSet).Include(p => p.Client);
            return View(await musicRadioIncDbContext.ToListAsync());
        }

        /// <summary>
        /// Detailses the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Details View</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var purchaseDetailEntity = await this._purcheaseDetaiRepository.Get()
                .Include(p => p.AlbumSet)
                .Include(p => p.Client)
                .FirstOrDefaultAsync(m => m.PurchaseDetailId == id);
            if (purchaseDetailEntity == null)
            {
                return NotFound();
            }

            return View(purchaseDetailEntity);
        }

        /// <summary>
        /// Creates the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Create By AlbumSetId</returns>
        public async Task<IActionResult> Create(int id)
        {
            try
            {
                var newPurcheaseDetail = await this._shopingServiceBL.ToPurcheaseDetail(id);
                var purcheaseCreated = await this._purcheaseDetaiRepository.Add(newPurcheaseDetail);
                await this._purcheaseDetaiRepository.SaveChangesAsync();
                return this.RedirectToAction(nameof(Details), new { id = purcheaseCreated.PurchaseDetailId });
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

CompuRent.DiegoTest.Presentation/Controllers/SearchController.cs
namespace CompuRent.DiegoTest.Presentation.Controllers
{
    using CompuRent.DiegoTest.Models.DTOs;
    using CompuRent.DiegoTest.Models.Enums;
    using CompuRent.DiegoTest.Services.BL.Facades;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.Threading.Tasks;

    /// <summary>
    /// Search Controller
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    public class SearchController : Controller
    {
        /// <summary>
        /// The search service
        /// </summary>
        private readonly ISearchServiceBL _searchService;

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchController"/> class.
        /// </summary>
        /// <param name="searchService">The search service.</param>
        public SearchController(ISearchServiceBL searchService)
        {
            this._searchService = searchService;
        }

        /// <summary>
        /// Indexes the specified search by.
        /// </summary>
        /// <param name="searchBy">The search by.</param>
        /// <param name="query">The query.</param>
        /// <returns>Partial View By Search</returns>
        public async Task<IActionResult> Index(SearchDTO searchDTO)
        {
            try
            {
                switch (searchDTO.SearchBy)
                {
                    case SearchBy.Song:
                    default:
                        var songResult = this._searchService.FindBySong(searchDTO.QueryToFilter);
                        return this.PartialView("SongSetResult", await songResult.ToListAsync());
                    case SearchBy.Album:
                        var albumResult = this._searchService.FindByAlbum(searchDTO.QueryToFilter);
                        return this.PartialView("AlbumSetResult", await albumResult.ToListAsync());
                }
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

CompuRent.DiegoTest.Presentation/Views/Search/AlbumSetResult.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@model IEnumerable<AlbumSetEntity>

<div class="card">
    <div class="card-header">
        Resultado de Búsqueda por <b>Álbum</b>
        @if (string.IsNullOrEmpty(HttpContextAccessor.HttpContext.Session.GetString("ClientId")))
        {
            <br />
            <div class="alert alert-primary" role="alert">
                Para comprar Álbumes, debes <a class="btn btn-outline-primary m-0 p-1" href="#" onclick="ToggleLogin()"><i class="fa fa-user"></i> Iniciar Sesión</a>
            </div>
        }
    </div>
    <div class="card-body">
        @if (Model.Any())
        {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        @if (!string.IsNullOrEmpty(HttpContextAccessor.HttpContext.Session.GetString("ClientId")))
                        {
                            <th>
                                Comprar
                            </th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            @if (!string.IsNullOrEmpty(HttpContextAccessor.HttpContext.Session.GetString("ClientId")))
                            {
                                <td>
                                    <a class="btn btn-outline-dark" asp-action="Create" asp-controller="PurchaseDetails" asp-route-id="@item.AlbumSetId"><i class="fa fa-plus-square"></i></a>
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div class="alert alert-info" role="alert">
                No hay resultados
            </div>
        }
    </div>
</div>

CompuRent.DiegoTest.Presentation/Views/Search/SongSetResult.cshtml
@model IEnumerable<SongSetEntity>
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<div class="card">
    <div class="card-header">
        Resultado de Búsqueda Por <b>Canción</b>
        @if (string.IsNullOrEmpty(HttpContextAccessor.HttpContext.Session.GetString("ClientId")))
        {
            <br />
            <div class="alert alert-primary" role="alert">
                Para comprar Álbumes, debes <a class="btn btn-outline-primary m-0 p-1" href="#" onclick="ToggleLogin()"><i class="fa fa-user"></i> Iniciar Sesión</a>
            </div>
        }
    </div>
    <div class="card-body">
        @if (Model.Any())
        {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.AlbumSet)
                        </th>
                        @if (!string.IsNullOrEmpty(HttpContextAccessor.HttpContext.Session.GetString("ClientId")))
                        {
                            <th>
                                Comprar Álbum
                            </th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AlbumSet.Name)
                            </td>
                            @if (!string.IsNullOrEmpty(HttpContextAccessor.HttpContext.Session.GetString("ClientId")))
                            {
                                <td>
                                    <a class="btn btn-outline-dark" asp-action="Create" asp-controller="PurchaseDetails" asp-route-id="@item.AlbumSetId"><i class="fa fa-plus-square"></i></a>
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div class="alert alert-info" role="alert">
                No hay resultados
            </div>
        }
    </div>
</div>